version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # The root directory of your project where your requirements.txt is located
    schedule:
      interval: "weekly" # Dependabot will check for updates weekly
    # You can add more options if needed, such as:
    # open-pull-requests-limit: 5
    # ignore:
    #   - dependency-name: "some-package"
    #     versions: ["1.x", "2.x"]
